//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab7b_forms.DictionaryService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Record", Namespace="http://belstu.by/")]
    [System.SerializableAttribute()]
    public partial class Record : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://belstu.by/", ConfigurationName="DictionaryService.DictionarySoap")]
    public interface DictionarySoap {
        
        // CODEGEN: Generating message contract since element name GetDictResult from namespace http://belstu.by/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://belstu.by/GetDict", ReplyAction="*")]
        lab7b_forms.DictionaryService.GetDictResponse GetDict(lab7b_forms.DictionaryService.GetDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://belstu.by/GetDict", ReplyAction="*")]
        System.Threading.Tasks.Task<lab7b_forms.DictionaryService.GetDictResponse> GetDictAsync(lab7b_forms.DictionaryService.GetDictRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://belstu.by/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://belstu.by/AddDict", ReplyAction="*")]
        lab7b_forms.DictionaryService.AddDictResponse AddDict(lab7b_forms.DictionaryService.AddDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://belstu.by/AddDict", ReplyAction="*")]
        System.Threading.Tasks.Task<lab7b_forms.DictionaryService.AddDictResponse> AddDictAsync(lab7b_forms.DictionaryService.AddDictRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://belstu.by/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://belstu.by/UpdDict", ReplyAction="*")]
        lab7b_forms.DictionaryService.UpdDictResponse UpdDict(lab7b_forms.DictionaryService.UpdDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://belstu.by/UpdDict", ReplyAction="*")]
        System.Threading.Tasks.Task<lab7b_forms.DictionaryService.UpdDictResponse> UpdDictAsync(lab7b_forms.DictionaryService.UpdDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://belstu.by/DelDict", ReplyAction="*")]
        void DelDict(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://belstu.by/DelDict", ReplyAction="*")]
        System.Threading.Tasks.Task DelDictAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDict", Namespace="http://belstu.by/", Order=0)]
        public lab7b_forms.DictionaryService.GetDictRequestBody Body;
        
        public GetDictRequest() {
        }
        
        public GetDictRequest(lab7b_forms.DictionaryService.GetDictRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDictRequestBody {
        
        public GetDictRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDictResponse", Namespace="http://belstu.by/", Order=0)]
        public lab7b_forms.DictionaryService.GetDictResponseBody Body;
        
        public GetDictResponse() {
        }
        
        public GetDictResponse(lab7b_forms.DictionaryService.GetDictResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://belstu.by/")]
    public partial class GetDictResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public lab7b_forms.DictionaryService.Record[] GetDictResult;
        
        public GetDictResponseBody() {
        }
        
        public GetDictResponseBody(lab7b_forms.DictionaryService.Record[] GetDictResult) {
            this.GetDictResult = GetDictResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDict", Namespace="http://belstu.by/", Order=0)]
        public lab7b_forms.DictionaryService.AddDictRequestBody Body;
        
        public AddDictRequest() {
        }
        
        public AddDictRequest(lab7b_forms.DictionaryService.AddDictRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://belstu.by/")]
    public partial class AddDictRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string number;
        
        public AddDictRequestBody() {
        }
        
        public AddDictRequestBody(string name, string number) {
            this.name = name;
            this.number = number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDictResponse", Namespace="http://belstu.by/", Order=0)]
        public lab7b_forms.DictionaryService.AddDictResponseBody Body;
        
        public AddDictResponse() {
        }
        
        public AddDictResponse(lab7b_forms.DictionaryService.AddDictResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddDictResponseBody {
        
        public AddDictResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdDictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdDict", Namespace="http://belstu.by/", Order=0)]
        public lab7b_forms.DictionaryService.UpdDictRequestBody Body;
        
        public UpdDictRequest() {
        }
        
        public UpdDictRequest(lab7b_forms.DictionaryService.UpdDictRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://belstu.by/")]
    public partial class UpdDictRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string number;
        
        public UpdDictRequestBody() {
        }
        
        public UpdDictRequestBody(int id, string name, string number) {
            this.id = id;
            this.name = name;
            this.number = number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdDictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdDictResponse", Namespace="http://belstu.by/", Order=0)]
        public lab7b_forms.DictionaryService.UpdDictResponseBody Body;
        
        public UpdDictResponse() {
        }
        
        public UpdDictResponse(lab7b_forms.DictionaryService.UpdDictResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdDictResponseBody {
        
        public UpdDictResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DictionarySoapChannel : lab7b_forms.DictionaryService.DictionarySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DictionarySoapClient : System.ServiceModel.ClientBase<lab7b_forms.DictionaryService.DictionarySoap>, lab7b_forms.DictionaryService.DictionarySoap {
        
        public DictionarySoapClient() {
        }
        
        public DictionarySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DictionarySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DictionarySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DictionarySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lab7b_forms.DictionaryService.GetDictResponse lab7b_forms.DictionaryService.DictionarySoap.GetDict(lab7b_forms.DictionaryService.GetDictRequest request) {
            return base.Channel.GetDict(request);
        }
        
        public lab7b_forms.DictionaryService.Record[] GetDict() {
            lab7b_forms.DictionaryService.GetDictRequest inValue = new lab7b_forms.DictionaryService.GetDictRequest();
            inValue.Body = new lab7b_forms.DictionaryService.GetDictRequestBody();
            lab7b_forms.DictionaryService.GetDictResponse retVal = ((lab7b_forms.DictionaryService.DictionarySoap)(this)).GetDict(inValue);
            return retVal.Body.GetDictResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<lab7b_forms.DictionaryService.GetDictResponse> lab7b_forms.DictionaryService.DictionarySoap.GetDictAsync(lab7b_forms.DictionaryService.GetDictRequest request) {
            return base.Channel.GetDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<lab7b_forms.DictionaryService.GetDictResponse> GetDictAsync() {
            lab7b_forms.DictionaryService.GetDictRequest inValue = new lab7b_forms.DictionaryService.GetDictRequest();
            inValue.Body = new lab7b_forms.DictionaryService.GetDictRequestBody();
            return ((lab7b_forms.DictionaryService.DictionarySoap)(this)).GetDictAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lab7b_forms.DictionaryService.AddDictResponse lab7b_forms.DictionaryService.DictionarySoap.AddDict(lab7b_forms.DictionaryService.AddDictRequest request) {
            return base.Channel.AddDict(request);
        }
        
        public void AddDict(string name, string number) {
            lab7b_forms.DictionaryService.AddDictRequest inValue = new lab7b_forms.DictionaryService.AddDictRequest();
            inValue.Body = new lab7b_forms.DictionaryService.AddDictRequestBody();
            inValue.Body.name = name;
            inValue.Body.number = number;
            lab7b_forms.DictionaryService.AddDictResponse retVal = ((lab7b_forms.DictionaryService.DictionarySoap)(this)).AddDict(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<lab7b_forms.DictionaryService.AddDictResponse> lab7b_forms.DictionaryService.DictionarySoap.AddDictAsync(lab7b_forms.DictionaryService.AddDictRequest request) {
            return base.Channel.AddDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<lab7b_forms.DictionaryService.AddDictResponse> AddDictAsync(string name, string number) {
            lab7b_forms.DictionaryService.AddDictRequest inValue = new lab7b_forms.DictionaryService.AddDictRequest();
            inValue.Body = new lab7b_forms.DictionaryService.AddDictRequestBody();
            inValue.Body.name = name;
            inValue.Body.number = number;
            return ((lab7b_forms.DictionaryService.DictionarySoap)(this)).AddDictAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lab7b_forms.DictionaryService.UpdDictResponse lab7b_forms.DictionaryService.DictionarySoap.UpdDict(lab7b_forms.DictionaryService.UpdDictRequest request) {
            return base.Channel.UpdDict(request);
        }
        
        public void UpdDict(int id, string name, string number) {
            lab7b_forms.DictionaryService.UpdDictRequest inValue = new lab7b_forms.DictionaryService.UpdDictRequest();
            inValue.Body = new lab7b_forms.DictionaryService.UpdDictRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.number = number;
            lab7b_forms.DictionaryService.UpdDictResponse retVal = ((lab7b_forms.DictionaryService.DictionarySoap)(this)).UpdDict(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<lab7b_forms.DictionaryService.UpdDictResponse> lab7b_forms.DictionaryService.DictionarySoap.UpdDictAsync(lab7b_forms.DictionaryService.UpdDictRequest request) {
            return base.Channel.UpdDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<lab7b_forms.DictionaryService.UpdDictResponse> UpdDictAsync(int id, string name, string number) {
            lab7b_forms.DictionaryService.UpdDictRequest inValue = new lab7b_forms.DictionaryService.UpdDictRequest();
            inValue.Body = new lab7b_forms.DictionaryService.UpdDictRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.number = number;
            return ((lab7b_forms.DictionaryService.DictionarySoap)(this)).UpdDictAsync(inValue);
        }
        
        public void DelDict(int id) {
            base.Channel.DelDict(id);
        }
        
        public System.Threading.Tasks.Task DelDictAsync(int id) {
            return base.Channel.DelDictAsync(id);
        }
    }
}
